---
- name: Set up PowerShell for fetching modules
  tags: prereqs
  ansible.builtin.win_shell: |
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
    Install-Module PowerShellGet -AllowClobber -Force
    Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

- name: "Ensure {{ mssql_domain_controller }} has SqlServer module"
  tags:
    - test
    - test_sql
  community.windows.win_psmodule:
    name: SqlServer
    state: present
    accept_license: true

- name: "Test connection with SQL query from {{ mssql_domain_controller }}"
  tags:
    - test
    - test_sql
  register: r_test_sql
  ansible.windows.win_shell: >
    Invoke-SqlCmd -Query "SELECT GETDATE() AS TimeOfQuery"
      -Server "{{ hostvars[inventory_hostname]['ansible_host'] }}"
      -TrustServerCertificate

- name: Print SQL output
  delegate_to: localhost
  tags:
    - test
    - test_sql
  ansible.builtin.debug:
    var: r_test_sql.stdout_lines